Repository 9oormthon-univ/2025_SEASONTHON_TEAM_3_BE, pull requests merged in 2025-09, with the labels that each got.

#20 [FEAT] 찜 관련 API 구현
  src/main/java/com/silver/domain/like/controller/LikeController.java
  src/main/java/com/silver/domain/like/dto/response/LikeToggleResponseDto.java
  src/main/java/com/silver/domain/like/dto/response/LikedSnackResponseDto.java
  src/main/java/com/silver/domain/like/entity/Like.java
  src/main/java/com/silver/domain/like/repository/LikeRepository.java
  src/main/java/com/silver/domain/like/service/LikeService.java
  src/main/java/com/silver/domain/like/service/LikeServiceImpl.java
Labels: feat

#21 [FEAT] 전체간식조회 해시태그 필터링 추가
  src/main/java/com/silver/domain/snack/controller/SnackController.java
  src/main/java/com/silver/domain/snack/repository/SnackRepository.java
  src/main/java/com/silver/domain/snack/service/SnackService.java
  src/main/resources/snacks_for_seniors_top100.csv
Labels: feat

#22 [FIX] v5: 간식 전체조회 해시태그 필터링 추가, 찜기능 추가
  src/main/java/com/silver/domain/like/controller/LikeController.java
  src/main/java/com/silver/domain/like/dto/response/LikeToggleResponseDto.java
  src/main/java/com/silver/domain/like/dto/response/LikedSnackResponseDto.java
  src/main/java/com/silver/domain/like/entity/Like.java
  src/main/java/com/silver/domain/like/repository/LikeRepository.java
  src/main/java/com/silver/domain/like/service/LikeService.java
  src/main/java/com/silver/domain/like/service/LikeServiceImpl.java
  src/main/java/com/silver/domain/snack/controller/SnackController.java
  src/main/java/com/silver/domain/snack/repository/SnackRepository.java
  src/main/java/com/silver/domain/snack/service/SnackService.java
  src/main/resources/application.yml
  src/main/resources/snacks_for_seniors_top100.csv
Labels: cicd, fix

#23 [CICD] v6: update로 수정
  src/main/resources/application.yml
Labels: cicd

#24 [CICD] v7: CORS 허용에 patch 추가
  src/main/java/com/silver/global/config/CorsConfig.java
Labels: cicd

#25 [FIX] 사용자 정보 기반의 간식 추천 기능 수정
  src/main/java/com/silver/domain/snack/controller/RecommendationController.java
  src/main/java/com/silver/domain/snack/dto/request/SnackRequestDTO.java
  src/main/java/com/silver/domain/snack/dto/response/SnackRecommendationDTO.java
  src/main/java/com/silver/domain/snack/repository/SnackRepository.java
  src/main/java/com/silver/domain/snack/service/RecommendationService.java
Labels: fix

#26 [FIX] v8: 사용자 정보 기반 추천 로직 변경
  src/main/java/com/silver/domain/snack/controller/RecommendationController.java
  src/main/java/com/silver/domain/snack/dto/request/SnackRequestDTO.java
  src/main/java/com/silver/domain/snack/dto/response/SnackRecommendationDTO.java
  src/main/java/com/silver/domain/snack/repository/SnackRepository.java
  src/main/java/com/silver/domain/snack/service/RecommendationService.java
Labels: fix
